### ISSUE TITLE
Support dry activation

### ISSUE THREAD

**Issue by Mynacol** [thefossguy/nixos-needsreboot#2]
I finally came around to using this project, thanks for sharing it.

If i [see it](https://github.com/thefossguy/nixos-needsreboot/blob/master/src/main.rs#L9) correctly, you always use `/nix/var/nix/profiles/system` as the new system path. Won't this give wrong results if we were to use it during dry-activate (comparing the current system instead of the dry-activated one)? Others and myself [try to use it this way](https://github.com/wimpysworld/nix-config/blob/main/nixos/default.nix#L374-L379).

I propose to use a cmdline argument as "new" path, if provided. Then the activation script can provide it with `$systemConfig` ([example](https://github.com/wimpysworld/nix-config/blob/main/nixos/default.nix#L377)). The old path always has to be `/run/booted-system` for obvious reasons.

**Comment by thefossguy** [comment]
On Sunday, March 24th, 2024 at 15:04, Mynacol ***@***.***> wrote:

> I finally came around to using this project, thanks for sharing it.
> 
> If i see it correctly, you always use `/nix/var/nix/profiles/system` as the new system path. Won't this give wrong results if we were to use it during dry-activate (comparing the current system instead of the dry-activated one)?

That's an error from my side actually. It's the reverse. Thanks for pointing it out!

> Others and myself try to use it this way.

Hmm, interesting way to use it. I use it as a nightly service, usually triggered by the successful completion of the `nixos-upgrade` service.

If you're switching to a new NixOS generation, I'm not sure if `/run` is preserved.

> I propose to use a cmdline argument as "new" path, if provided. Then the activation script can provide it with `$systemConfig` (example). The old path always has to be `/run/booted-system` for obvious reasons.

This sounds like a good solution. Thank you.

Do you plan on sending a PR or should I go ahead and fix this (attributing the mention and solution to you)? **No pressure**, just don't want to overreach and waste your time if you have a PR ready.

 -- Pratham Patel

**Comment by thefossguy** [comment]
Are your issues addressed with `0.1.5`?

**Comment by thefossguy** [comment]
I actually built this with the intention of a binary that runs in a systemd service (i.e. after `nixos-upgrade.service`). Doing so means I don't need to account for a lot of moving parts :)

There's https://github.com/NixOS/nixpkgs/pull/303764 that demonstrates how it's intended to be used.
