### ISSUE TITLE
Bump version in flake

### ISSUE THREAD

**Issue by the-furry-hubofeverything** [thefossguy/nixos-needsreboot#3]
Hi!

I'm using your program in my nixos config.

I get a hash mismatch when I tried to build it:
```console
error: hash mismatch in fixed-output derivation '/nix/store/mclbqnc6spncgpxcjk54lizns2h3s5pk-nixos-needsreboot-0.1.4-vendor.tar.gz.drv':
         specified: sha256-jW2ul5dXWPQpdIL39yIYVNP7D65NAFZ8q40Zy6tYMj8=
            got:    sha256-Q6a0MGv7IWdwQvu83HxRYVzBvJRUcIl3rIXng7vRGmI=
error: 1 dependencies of derivation '/nix/store/xksbxccj4bpxc65s311cq4s4mmrjrmqf-nixos-needsreboot-0.1.4.drv' failed to build
error: 1 dependencies of derivation '/nix/store/8qdxrsikr04zwnmcg3bzgq06ck2q64vc-system-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/2jpkya2cbv6vb5hrcnrxq8gvmbvpjjk5-nixos-system-Gulo-Laptop-23.11.20240411.51651a5.drv' failed to build
```

Then I took a look at the flake.nix and noticed that you forgot to bump the version after the releases. Might be good to check the rust lock files too, but I don't know how those work.

**Comment by thefossguy** [comment]
Ah yes, I forgot to deal with the flake in upstreaming this to nixpkgs. Sorry about that, `0.1.8` should address it for you. If it does, please close this issue. If not, please inform me what else is broken.

**Comment by the-furry-hubofeverything** [comment]
That did it, thank you!
